# Generated by Django 4.1.3 on 2022-12-22 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_collaborator_exam_examquestion_multiplechoiceoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.collaborator'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.student'),
        ),
    ]
