# Generated by Django 4.1.3 on 2022-12-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_category_examquestion_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoiceoption',
            old_name='text',
            new_name='option_text',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='multiplechoiceoption',
            name='option_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
