# Generated by Django 4.1.3 on 2022-12-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_rename_text_multiplechoiceoption_option_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
