# Generated by Django 4.1.3 on 2022-12-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_subcategory_examquestion_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='exams', to='Project.category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='exams', to='Project.subcategory'),
        ),
    ]
