# Generated by Django 4.1.3 on 2022-12-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_exam_categories_exam_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.subcategory'),
        ),
    ]
