# Generated by Django 4.1.3 on 2022-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_remove_exam_category_remove_exam_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exams',
            field=models.ManyToManyField(blank=True, to='Project.exam'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='exams',
            field=models.ManyToManyField(blank=True, to='Project.exam'),
        ),
    ]
