# Generated by Django 4.1.3 on 2023-01-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_category_exams_subcategory_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.explanation'),
        ),
    ]
