# Generated by Django 4.1.3 on 2023-01-20 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_alter_examquestion_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
