# Generated by Django 4.1.3 on 2023-01-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_alter_university_country'),
    ]

    operations = [
    ]
