# Generated by Django 4.1.3 on 2023-01-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_auto_20230126_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='country',
        ),
    ]
