# Generated by Django 4.1.3 on 2023-01-27 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0018_collaborator_student_remove_exam_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration',
        ),
        migrations.AddField(
            model_name='exam',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
