# Generated by Django 4.1.3 on 2023-01-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0019_remove_exam_date_remove_exam_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborator',
            old_name='date_of_birth',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='date_of_birth',
            new_name='birthday',
        ),
    ]
