# Generated by Django 4.1.3 on 2023-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0021_remove_exam_time_exam_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='exams',
        ),
    ]
