# Generated by Django 4.1.3 on 2023-01-31 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0022_remove_category_exams_remove_subcategory_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.CreateModel(
            name='ExamSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.exam')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.category')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.exam')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ManyToManyField(blank=True, to='Project.student'),
        ),
    ]
