# Generated by Django 4.1.3 on 2023-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0023_remove_exam_student_examsubcategory_examcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='collaborator',
        ),
        migrations.AddField(
            model_name='exam',
            name='collaborator',
            field=models.ManyToManyField(blank=True, to='Project.collaborator'),
        ),
    ]
