# Generated by Django 4.1.3 on 2023-01-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0025_rename_collaborator_exam_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='multiplechoiceoption',
            name='option_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
