# Generated by Django 4.1.3 on 2023-02-09 22:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0026_alter_examquestion_image_alter_explanation_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.student')),
            ],
        ),
    ]
