# Generated by Django 4.1.3 on 2023-02-28 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0027_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examresult',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
