# Generated by Django 4.1.3 on 2023-02-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0028_examresult_date_examresult_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='duration',
        ),
    ]
