# Generated by Django 4.1.3 on 2023-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0029_remove_examresult_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
