# Generated by Django 4.1.3 on 2023-02-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0030_examresult_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
