# Generated by Django 4.1.3 on 2023-02-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0031_alter_examresult_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamResult',
        ),
    ]
