# Generated by Django 4.1.3 on 2023-02-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0033_examresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='exam_session',
        ),
    ]
