# Generated by Django 4.1.3 on 2023-03-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0034_remove_examresult_exam_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='answers',
            field=models.ManyToManyField(blank=True, to='Project.studentanswer'),
        ),
    ]
