# Generated by Django 4.1.7 on 2023-03-13 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0037_exam_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='explanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='Project.explanation'),
        ),
        migrations.AlterField(
            model_name='explanation',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='Project.exam'),
        ),
    ]
