# Generated by Django 4.1.7 on 2023-03-19 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0038_alter_examquestion_explanation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explanation',
            name='exam',
        ),
        migrations.AddField(
            model_name='explanation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='explanations_question', to='Project.examquestion'),
        ),
    ]
