# Generated by Django 4.1.7 on 2023-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0041_alter_explanation_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
