# Generated by Django 4.1.7 on 2023-03-25 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0042_examsession_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.student')),
            ],
        ),
    ]
