# Generated by Django 4.1.7 on 2023-03-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0043_examstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamStudent',
        ),
    ]
