# Generated by Django 4.1.7 on 2023-04-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0048_studentanswer_exam_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='admision_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='exams',
            field=models.ManyToManyField(blank=True, related_name='exams', to='Project.exam'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_university', to='Project.university')),
            ],
        ),
        migrations.CreateModel(
            name='CarrerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrer_types_university', to='Project.university')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carrer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers_carrer_type', to='Project.carrertype')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='careers_university', to='Project.university')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='careers',
            field=models.ManyToManyField(blank=True, related_name='careers', to='Project.career'),
        ),
        migrations.AddField(
            model_name='university',
            name='carrer_types',
            field=models.ManyToManyField(blank=True, related_name='carrer_types', to='Project.carrertype'),
        ),
        migrations.AddField(
            model_name='university',
            name='social_media',
            field=models.ManyToManyField(blank=True, related_name='social_media', to='Project.socialmedia'),
        ),
    ]
