# Generated by Django 4.1.7 on 2023-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0049_university_admision_link_university_exams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
