# Generated by Django 4.1.7 on 2023-04-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0050_alter_examresult_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
