# Generated by Django 4.1.7 on 2023-04-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0051_examquestion_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
