# Generated by Django 4.1.7 on 2023-04-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0052_alter_examquestion_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='carrertype',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
