# Generated by Django 4.1.7 on 2023-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0053_alter_career_name_alter_carrertype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='orden',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
